# Generated by Django 6.0.4 on 2026-04-09 07:31

import apps.crm.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Статус события',
                'verbose_name_plural': 'Статусы событий',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InteractionObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Тип объекта взаимодействия',
                'verbose_name_plural': 'Типы объектов взаимодействия',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InteractionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Статус взаимодействия',
                'verbose_name_plural': 'Статусы взаимодействия',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Статус организации',
                'verbose_name_plural': 'Статусы организаций',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Тип организации',
                'verbose_name_plural': 'Типы организаций',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrmVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Производитель ТС ОРМ',
                'verbose_name_plural': 'Производители ТС ОРМ',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsiStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Статус ПСИ',
                'verbose_name_plural': 'Статусы ПСИ',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SormOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Владелец СОРМ',
                'verbose_name_plural': 'Владельцы СОРМ',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование организации')),
                ('inn', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ИНН')),
                ('case_number', models.CharField(blank=True, max_length=128, verbose_name='Номер дела')),
                ('responsible_person', models.CharField(blank=True, max_length=255, verbose_name='Ответственное лицо')),
                ('in_registry', models.CharField(blank=True, max_length=255, verbose_name='Наличие в реестре')),
                ('registry_record_url', models.URLField(blank=True, verbose_name='Ссылка на запись в реестре')),
                ('site_legacy', models.TextField(blank=True, verbose_name='Сайт (legacy)')),
                ('correspondence_address', models.TextField(blank=True, verbose_name='Адрес для корреспонденции')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='crm.industry', verbose_name='Отрасль')),
                ('interaction_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='crm.interactionstatus', verbose_name='Статус взаимодействия')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='crm.organizationstatus', verbose_name='Статус')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='crm.organizationtype', verbose_name='Тип организации')),
                ('orm_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='crm.ormvendor', verbose_name='Производитель ТС ОРМ')),
                ('sorm_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='crm.sormowner', verbose_name='Владелец СОРМ')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=120, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=11, validators=[apps.crm.validators.validate_phone_11_digits], verbose_name='Телефонный номер')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Адрес электронной почты')),
                ('extra_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('commented_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-commented_at',),
            },
        ),
        migrations.CreateModel(
            name='Psi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('assigned_date', models.DateField(blank=True, null=True, verbose_name='Дата назначения')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('protocol_html_url', models.URLField(blank=True, verbose_name='Ссылка на протокол')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psis', to='crm.organization', verbose_name='Организация')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='psis', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='psis', to='crm.psistatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'ПСИ',
                'verbose_name_plural': 'ПСИ',
            },
        ),
        migrations.CreateModel(
            name='EventDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование шаблона')),
                ('template_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к шаблону .docx')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='crm.eventtype', verbose_name='Тип события')),
            ],
            options={
                'verbose_name': 'Шаблон документа события',
                'verbose_name_plural': 'Шаблоны документов событий',
                'constraints': [models.UniqueConstraint(fields=('event_type', 'name'), name='uniq_event_template_name')],
            },
        ),
        migrations.CreateModel(
            name='InteractionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Завершение действия')),
                ('object_value', models.CharField(max_length=500, verbose_name='Объект взаимодействия')),
                ('object_url', models.URLField(blank=True, verbose_name='Ссылка на объект')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_objects', to='crm.interactionobjecttype', verbose_name='Тип объекта')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_objects', to='crm.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Объект взаимодействия',
                'verbose_name_plural': 'Объекты взаимодействия',
                'indexes': [models.Index(fields=['organization', 'object_type'], name='crm_interac_organiz_8b7ec7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='interaction_dates_valid')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.contact', verbose_name='Контакт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_events', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_events', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='crm.eventstatus', verbose_name='Статус')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='crm.eventtype', verbose_name='Событие')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'indexes': [models.Index(fields=['organization', 'event_date'], name='crm_event_organiz_ad3702_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Завершение действия')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='Номер документа')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование документа')),
                ('html_url', models.URLField(blank=True, verbose_name='Ссылка на HTML документ')),
                ('text_url', models.URLField(blank=True, verbose_name='Ссылка на текстовый документ')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Файл')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='crm.documenttype', verbose_name='Документ')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='document_dates_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'last_name'], name='crm_contact_organiz_5ed4e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='psi',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='psi_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['inn'], name='crm_organiz_inn_1ea363_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='crm_organiz_name_875d18_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('inn', 'name'), name='uniq_org_inn_name'),
        ),
    ]
