# Generated by Django 6.0.4 on 2026-06-11 15:28

import apps.crm.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Статус события',
                'verbose_name_plural': 'Статусы событий',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InteractionObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Тип объекта взаимодействия',
                'verbose_name_plural': 'Типы объектов взаимодействия',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseOrderNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Номер приказа',
                'verbose_name_plural': 'Номера приказов',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrmVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Синоним для импорта')),
            ],
            options={
                'verbose_name': 'Производитель ТС ОРМ',
                'verbose_name_plural': 'Производители ТС ОРМ',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=11, validators=[apps.crm.validators.validate_phone_11_digits], verbose_name='Телефонный номер')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Адрес электронной почты')),
                ('extra_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='data_sources/icons/', verbose_name='Иконка')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('inn', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ИНН')),
                ('case_number', models.CharField(blank=True, max_length=128, verbose_name='Номер дела')),
                ('sites', models.JSONField(blank=True, default=list, validators=[apps.crm.validators.validate_url_list], verbose_name='Сайты')),
                ('correspondence_address', models.TextField(blank=True, verbose_name='Адрес для корреспонденции')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_data_sources', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to='crm.industry', verbose_name='Отрасль')),
            ],
            options={
                'verbose_name': 'Источник данных',
                'verbose_name_plural': 'Источники данных',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='organizations/icons/', verbose_name='Иконка')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование организации')),
                ('inn', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ИНН')),
                ('case_number', models.CharField(blank=True, max_length=128, verbose_name='Номер дела')),
                ('outsourcing', models.BooleanField(default=False, verbose_name='Аутсорминг')),
                ('in_registry', models.CharField(blank=True, max_length=255, verbose_name='Номер в реестре')),
                ('registry_record_url', models.URLField(blank=True, verbose_name='Ссылка на запись в реестре')),
                ('sites', models.JSONField(blank=True, default=list, validators=[apps.crm.validators.validate_url_list], verbose_name='Сайты')),
                ('correspondence_address', models.TextField(blank=True, verbose_name='Адрес для корреспонденции')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='crm.industry', verbose_name='Отрасль')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
                ('sorm_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorm_children', to='crm.ori', verbose_name='Владелец СОРМ')),
                ('orm_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='crm.ormvendor', verbose_name='Производитель ТС ОРМ')),
            ],
            options={
                'verbose_name': 'ОРИ',
                'verbose_name_plural': 'ОРИ',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.contact', verbose_name='Контакт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_events', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_events', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='crm.eventstatus', verbose_name='Статус')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='crm.eventtype', verbose_name='Событие')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.ori', verbose_name='ОРИ')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.ori', verbose_name='ОРИ'),
        ),
        migrations.CreateModel(
            name='LicenseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_orders', to='crm.licenseordernumber', verbose_name='Номер приказа')),
                ('orm_vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_orders', to='crm.ormvendor', verbose_name='Производитель ТС (ИС) ОРМ')),
            ],
            options={
                'verbose_name': 'Приказ лицензии',
                'verbose_name_plural': 'Приказы лицензий',
                'ordering': ('license', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Psi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('assigned_date', models.DateField(blank=True, null=True, verbose_name='Дата назначения')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('assigned', 'Назначены'), ('in_progress', 'В работе'), ('failed', 'Провалены'), ('overdue', 'Просрочены'), ('successful', 'Успешны')], default='assigned', max_length=24, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('license_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psis', to='crm.licenseorder', verbose_name='Приказ лицензии')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psis', to='crm.ori', verbose_name='ОРИ')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='psis', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'ПСИ',
                'verbose_name_plural': 'ПСИ',
            },
        ),
        migrations.CreateModel(
            name='TelecomOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='telecom_operators/icons/', verbose_name='Иконка')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование организации')),
                ('inn', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ИНН')),
                ('case_number', models.CharField(blank=True, max_length=128, verbose_name='Номер дела')),
                ('sites', models.JSONField(blank=True, default=list, validators=[apps.crm.validators.validate_url_list], verbose_name='Сайты')),
                ('correspondence_address', models.TextField(blank=True, verbose_name='Адрес для корреспонденции')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_telecom_operators', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Оператор связи',
                'verbose_name_plural': 'Операторы связи',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='telecom_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_contacts', to='crm.telecomoperator', verbose_name='Оператор связи'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('commented_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.datasource', verbose_name='Источник данных')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.ori', verbose_name='ОРИ')),
                ('telecom_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_comments', to='crm.telecomoperator', verbose_name='Оператор связи')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-commented_at',),
            },
        ),
        migrations.CreateModel(
            name='TelecomOperatorAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('event_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=16, verbose_name='Тип события')),
                ('operator_name', models.CharField(blank=True, max_length=500, verbose_name='Наименование оператора')),
                ('telecom_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='crm.telecomoperator', verbose_name='Оператор связи')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telecom_operator_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие аудита оператора связи',
                'verbose_name_plural': 'События аудита операторов связи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelecomOperatorLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='Номер')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание действия')),
                ('territory', models.TextField(blank=True, verbose_name='Территория действия')),
                ('status', models.CharField(choices=[('active', 'Действующая'), ('inactive', 'Недействующая')], default='active', max_length=16, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('telecom_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='crm.telecomoperator', verbose_name='Оператор связи')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ('telecom_operator', 'start_date', 'title'),
            },
        ),
        migrations.AddField(
            model_name='licenseorder',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.telecomoperatorlicense', verbose_name='Лицензия'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['inn'], name='crm_datasou_inn_9b67dc_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['name'], name='crm_datasou_name_ac1d5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('inn', 'name'), name='uniq_data_source_inn_name'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'event_date'], name='crm_event_organiz_ad3702_idx'),
        ),
        migrations.AddIndex(
            model_name='ori',
            index=models.Index(fields=['inn'], name='crm_ori_inn_4f96b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ori',
            index=models.Index(fields=['name'], name='crm_ori_name_b0c87a_idx'),
        ),
        migrations.AddConstraint(
            model_name='ori',
            constraint=models.UniqueConstraint(fields=('inn', 'name'), name='uniq_org_inn_name'),
        ),
        migrations.AddConstraint(
            model_name='psi',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='psi_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='psi',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('license_order__isnull', True), ('organization__isnull', False)), models.Q(('license_order__isnull', False), ('organization__isnull', True)), _connector='OR'), name='psi_single_scope'),
        ),
        migrations.AddIndex(
            model_name='telecomoperator',
            index=models.Index(fields=['inn'], name='crm_telecom_inn_641714_idx'),
        ),
        migrations.AddIndex(
            model_name='telecomoperator',
            index=models.Index(fields=['name'], name='crm_telecom_name_a29d10_idx'),
        ),
        migrations.AddConstraint(
            model_name='telecomoperator',
            constraint=models.UniqueConstraint(fields=('inn', 'name'), name='uniq_telecom_operator_inn_name'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'first_name'], name='crm_contact_organiz_9f9765_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['telecom_operator', 'first_name'], name='crm_contact_telecom_21b67a_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('telecom_operator__isnull', True)), models.Q(('organization__isnull', True), ('telecom_operator__isnull', False)), _connector='OR'), name='contact_org_xor_operator'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('data_source__isnull', True), ('organization__isnull', False), ('telecom_operator__isnull', True)), models.Q(('data_source__isnull', True), ('organization__isnull', True), ('telecom_operator__isnull', False)), models.Q(('data_source__isnull', False), ('organization__isnull', True), ('telecom_operator__isnull', True)), _connector='OR'), name='comment_single_scope'),
        ),
        migrations.AddIndex(
            model_name='telecomoperatorauditevent',
            index=models.Index(fields=['created_at'], name='crm_telecom_created_cc4822_idx'),
        ),
        migrations.AddIndex(
            model_name='telecomoperatorauditevent',
            index=models.Index(fields=['event_type'], name='crm_telecom_event_t_4c33d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='telecomoperatorlicense',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='telecom_license_dates_valid'),
        ),
    ]
