# Generated by Django 6.0.4 on 2026-04-09 08:59

import apps.crm.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='sorm_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorm_children', to='crm.organization', verbose_name='Владелец СОРМ'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='text_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='site_legacy',
        ),
        migrations.AddField(
            model_name='organization',
            name='sites',
            field=models.JSONField(blank=True, default=list, validators=[apps.crm.validators.validate_url_list], verbose_name='Сайты'),
        ),
        migrations.AlterField(
            model_name='interactionobject',
            name='object_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Ссылка на объект'),
        ),
        migrations.DeleteModel(
            name='SormOwner',
        ),
    ]
