# Generated by Django 6.0.4 on 2026-06-12 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('task', models.CharField(max_length=500, verbose_name='Задача')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('done', 'Готово'), ('overdue', 'Просрочено')], default='planned', max_length=16, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_actions', to='crm.datasource', verbose_name='Источник данных')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_actions', to='crm.ori', verbose_name='ОРИ')),
                ('telecom_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_actions', to='crm.telecomoperator', verbose_name='Оператор связи')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'ordering': ('deadline', 'pk'),
                'indexes': [models.Index(fields=['organization', 'deadline'], name='crm_orgacti_organiz_fa5747_idx'), models.Index(fields=['telecom_operator', 'deadline'], name='crm_orgacti_telecom_bcfdbb_idx'), models.Index(fields=['data_source', 'deadline'], name='crm_orgacti_data_so_50e6f8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('data_source__isnull', True), ('organization__isnull', False), ('telecom_operator__isnull', True)), models.Q(('data_source__isnull', True), ('organization__isnull', True), ('telecom_operator__isnull', False)), models.Q(('data_source__isnull', False), ('organization__isnull', True), ('telecom_operator__isnull', True)), _connector='OR'), name='org_action_single_scope')],
            },
        ),
    ]
