# Generated by Django 6.0.4 on 2026-04-09 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_responsible_person_to_user_id(apps, schema_editor):
    Organization = apps.get_model("crm", "Organization")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    for organization in Organization.objects.exclude(responsible_person__isnull=True).exclude(responsible_person=""):
        username = str(organization.responsible_person).strip()[:150]
        if not username:
            organization.responsible_person = None
            organization.save(update_fields=["responsible_person"])
            continue

        user, _ = User.objects.get_or_create(username=username)
        organization.responsible_person = str(user.pk)
        organization.save(update_fields=["responsible_person"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_organization_sorm_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_responsible_person_to_user_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organization',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо'),
        ),
    ]
