# Generated by Django 5.2.4 on 2026-04-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_organization_responsible_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/icons/', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='organization_types/icons/', verbose_name='Иконка'),
        ),
    ]
