# Generated by Django 5.2.4 on 2026-04-12 06:03

from django.db import migrations, models


def copy_status_to_statuses(apps, schema_editor):
    Organization = apps.get_model("crm", "Organization")
    through_model = Organization.statuses.through

    rows = []
    for organization in Organization.objects.exclude(status_id__isnull=True).only("id", "status_id"):
        rows.append(through_model(organization_id=organization.id, organizationstatus_id=organization.status_id))

    if rows:
        through_model.objects.bulk_create(rows, ignore_conflicts=True)


def reverse_copy_status_to_statuses(apps, schema_editor):
    Organization = apps.get_model("crm", "Organization")
    through_model = Organization.statuses.through
    for organization in Organization.objects.all().only("id"):
        first_row = (
            through_model.objects.filter(organization_id=organization.id)
            .order_by("id")
            .values_list("organizationstatus_id", flat=True)
            .first()
        )
        if first_row:
            Organization.objects.filter(id=organization.id).update(status_id=first_row)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_organization_icon_organizationtype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='organizations_by_statuses', to='crm.organizationstatus', verbose_name='Статусы'),
        ),
        migrations.RunPython(copy_status_to_statuses, reverse_copy_status_to_statuses),
        migrations.RemoveField(
            model_name='organization',
            name='status',
        ),
    ]
