# Generated by Django 6.0.4 on 2026-06-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_contact_data_source_scope'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='crm_contact_data_so_293ae5_idx',
            old_name='crm_contact_ds_fn_idx',
        ),
    ]
