# Generated by Django 6.0.4 on 2026-06-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_remove_interactionobjecttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InteractionObjectType',
        ),
    ]
