# Generated by Django 6.0.4 on 2026-07-01 07:33

from django.db import migrations, models


def create_default_app_settings(apps, schema_editor):
    AppSettings = apps.get_model("crm", "AppSettings")
    AppSettings.objects.get_or_create(
        pk=1,
        defaults={"responsibility_region": "Краснодарский край"},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_remove_ori_registry_record_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_region', models.CharField(blank=True, default='', max_length=255, verbose_name='Регион ответственности')),
            ],
            options={
                'verbose_name': 'Настройки приложения',
                'verbose_name_plural': 'Настройки приложения',
            },
        ),
        migrations.RunPython(create_default_app_settings, migrations.RunPython.noop),
    ]
